// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SchoolFaq.Core.Data;
using System;

namespace SchoolFaq.Core.Migrations
{
    [DbContext(typeof(FaqContext))]
    [Migration("20180303121417_b759703788844ef3aaaf07c8861b80c3")]
    partial class b759703788844ef3aaaf07c8861b80c3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SchoolFaq.Core.Models.FaqQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DislikesCount");

                    b.Property<int>("LikesCount");

                    b.Property<string>("QuestionerName");

                    b.Property<string>("QuestionerPhone");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("FaqQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
