// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SchoolFaq.Core.Data;
using System;

namespace SchoolFaq.Core.Migrations
{
    [DbContext(typeof(FaqContext))]
    [Migration("20180303174357_c54d7927d0e647fda0c303314421267b")]
    partial class c54d7927d0e647fda0c303314421267b
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SchoolFaq.Core.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SchoolFaq.Core.Models.FaqQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<DateTime?>("AnswerDate");

                    b.Property<string>("AnswererName");

                    b.Property<long>("CategoryId");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<int>("DislikesCount");

                    b.Property<int>("LikesCount");

                    b.Property<string>("QuestionerName");

                    b.Property<string>("QuestionerPhone");

                    b.Property<string>("Subject");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FaqQuestions");
                });

            modelBuilder.Entity("SchoolFaq.Core.Models.FaqQuestion", b =>
                {
                    b.HasOne("SchoolFaq.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
